# Generated by Django 4.0.5 on 2022-07-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='unit_price',
        ),
    ]
