# Generated by Django 4.0.5 on 2022-07-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_price_products_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='zip',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
