# Generated by Django 4.0.5 on 2022-07-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_addresses_zip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['last_name', 'first_name'], name='store_custo_last_na_e6a359_idx'),
        ),
    ]
