# Generated by Django 4.0.5 on 2022-07-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customers_store_custo_last_na_e6a359_idx'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO store_collections (title) 
                VALUES ('collection1');
        ""","""
            DELETE FROM store_collections 
            WHERE title='collection1';
        """)
    ]
